FORMAT: 1A
HOST: http://somedemo.com/api/

# Demo API

This is a demo introduction

## Quick Start

Sample code here with instructions

## Auth (OAuth 2)

+ scopes
    + user - A user scope, allowing you access to read the user information
    + user.email - A user scope, allowing you access to read the user's email addresses

## Group Todos
Todos is a way to manage tasks

+ Authenticated (Auth[user])

<!--+ Authenticated (Basic)-->
<!--    + username: kyle-->
<!--    + password: b2952d03bda09cb5f63b0162fbbee77c-->


<!--### Authorization [GET /authorize]-->

<!--+ Relation: authorize-->
<!--+ Request-->
<!--    + Parameters-->
<!--        + `response_type`: code (Response Type, required)-->
<!--        + `client_id`: b58051708627fa6a5b7e49108f3c7574 (Client ID, required)-->
<!--        + state (State)-->
<!--        + scope (Scope)-->
<!--        + `redirect_uri` (Redirect Callback, required)-->

<!--+ Redirect-->
<!--    + Parameters-->
<!--        + code (Code)-->
<!--        + state (State)-->


###Todos Collection [/todo]

#### List All Todos [GET]
Get a list of all todos for this user

+ Response 200 (application/json)

        [
            {
                "Key": "bbaa019f-ac7f-4ccf-a40d-a5c31a4dd796",
                "Name": "Item1",
                "IsComplete": false
            },
            {
                "Key": "abca019f-bc9f-3ccf-d40d-b7c31a4dd852",
                "Name": "Item2",
                "IsComplete": true
            }
        ]
        
#### Create a New Todo [POST]
You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)
    + Headers
    
            Authorization : Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY
        
    + Attributes (Todo)

+ Response 201 (application/json)

    + Headers

            Location: /todo/bbaa019f-ac7f-4ccf-a40d-a5c31a4dd796

    + Body

            {
                "Key": "bbaa019f-ac7f-4ccf-a40d-a5c31a4dd796",
                "Name": "Item1",
                "IsComplete": false
            }

### Todo [/todo/{todoId}]

#### Get a Todo by id [GET]
Get a Todo by Id
+ Parameters
    + todoId:'bbaa019f-ac7f-4ccf-a40d-a5c31a4dd79' (string, required) - ID of the todo

+ Response 200 (application/json)

    + Body

            {
                "Key": "bbaa019f-ac7f-4ccf-a40d-a5c31a4dd796",
                "Name": "Item1",
                "IsComplete": false
            }

### Data Structures
#### Todo
+ Name (required, string) ... description of todo
+ IsComplete (required, boolean) ... whether the todo is complete 

## Group Questions

### Questions Collection [/questions]

#### List All Questions [GET]
List all Questions

+ Response 200 (application/json)

        {
            "question": "Favorite programming language?",
            "choices": [
                {
                    "choice": "Swift",
                    "votes": 2048
                }, {
                    "choice": "Python",
                    "votes": 1024
                }
            ]
        }
        
#### Create a New Question [POST]
You may create your own question using this action.
This action takes a JSON payload as part of the request.
Response then return specific header and body.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/1

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2014-11-11T08:40:51.620Z",
                "url": "/questions/1",
                "choices": [
                    {
                        "choice": "Swift",
                        "url": "/questions/1/choices/1",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "url": "/questions/1/choices/2",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "url": "/questions/1/choices/3",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "url": "/questions/1/choices/4",
                        "votes": 0
                    }
                ]
            }